ASP.NET PrL/Models/ErrorViewModel.cs
namespace ASP.NET_PrL.Models;

public class ErrorViewModel
{
    public string RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

ASP.NET PrL/Controllers/AccountsController.cs
using BLL.Abstractions.Interfaces.UserInterfaces;
using Core.DataClasses;
using Core.Models.UserModels;
using Microsoft.AspNetCore.Mvc;

namespace ASP.NET_PrL.Controllers;

public class AccountsController : Controller
{
    private readonly ILoginService loginService;

    private readonly IRegistrationService registrationService;

    private readonly IAccountActivationService activationService;

    public AccountsController(ILoginService loginService, IRegistrationService registrationService, IAccountActivationService activationService)
    {
        this.loginService = loginService;
        this.registrationService = registrationService;
        this.activationService = activationService;
    }

    [HttpGet]
    public IActionResult Index()
    {
        return View("Login");
        // return (User.Identity?.IsAuthenticated ?? false) ? Ok() : View("Login");
        // replace ok with home account page
    }

    [HttpGet]
    public IActionResult Login()
    {
        if (User.Identity?.IsAuthenticated ?? false)
        {
            return Redirect("/Home");
        }
        return View(); // ToDo: redirect to account page
    }

    [HttpPost]
    public async Task<IActionResult> Login([FromForm] UserLoginModel loginData)
    {
        if (!ModelState.IsValid)
        {
            return View(loginData);
        }

        var tokenResult = await this.loginService.Login(loginData);
        if (!tokenResult.IsSuccess)
        {
            ViewData["Message"] = tokenResult.ExceptionMessage;
        }
        else
        {
            Response.Cookies.Append("token", tokenResult.Value);
        }

        return Redirect("/Home"); // ToDo: redirect to account page
    }

    [HttpGet]
    public IActionResult Register()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Register([FromForm] UserRegistrationModel registrationModel)
    {
        if (!ModelState.IsValid)
        {
            return View(registrationModel);
        }

        var result = await this.registrationService.Register(registrationModel);
        if (!result.IsSuccess)
        {
            ViewData["Message"] = result.ExceptionMessage;
            return View(registrationModel);
        }

        ModelState.Clear();
        ViewData["Message"] = "You were registered successfully. An activation link was sent to your email.";
        return View();
    }

    [HttpGet]
    public IActionResult Logout()
    {
        Response.Cookies.Delete("token");

        return Redirect("/");
    }

    [HttpGet]
    [Route("/Accounts/Activate/{uidb64}/{token}")]
    public async Task<IActionResult> Activate(string uidb64, string token)
    {
        var payload = new AccountActivationPayload()
        {
            Uidb64 = uidb64,
            Token = token,
        };

        var result = await this.activationService.Activate(payload);
        if (!result.IsSuccess)
        {
            ViewData["Message"] = "Invalid link.";
        }

        ViewData["Message"] = "Account activated successfully.";
        return View();
    }
}

ASP.NET PrL/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ASP.NET_PrL.Models;
using Microsoft.AspNetCore.Authorization;

namespace ASP.NET_PrL.Controllers;

public class HomeController : Controller
{
    public IActionResult Index()
    {
        return View();
    }

    [Authorize]
    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

ASP.NET PrL/Views/Accounts/Activate.cshtml
@{
    ViewData["Title"] = "Account activation";
}

<div class="text-center">
    <h3 class="display-6">@ViewData["Message"]</h3>
    <p><a asp-action="Login" asp-controller="Accounts">Login</a> now.</p>
</div>

ASP.NET PrL/Views/Accounts/Login.cshtml
@{
    ViewData["Title"] = "Login page";
}

@model Core.Models.UserModels.UserLoginModel


<div class="row">
    <div class="col-md-4">
        <form asp-action="Login" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-primary" />
            </div>
            <div>
                <p>@ViewData["Message"]</p>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

ASP.NET PrL/Views/Accounts/Register.cshtml
@model Core.Models.UserModels.UserRegistrationModel

@{
    ViewBag.Title = "Registration";
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Register" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control"/>
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control"/>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control"/>
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RePassword" class="control-label"></label>
                <input asp-for="RePassword" class="form-control"/>
                <span asp-validation-for="RePassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-primary"/>
            </div>
            <div class="form-group text-center">
                <p class="form-text">@ViewData["Message"]</p>
            </div>
        </form>
    </div>
</div>

ASP.NET PrL/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>It's an slack on minimals app. Register to start using.</p>
</div>

ASP.NET PrL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] -SlackOnMinimals</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/ASP.NET_PrL.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SlackOnMinimals</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    @if (User.Identity?.IsAuthenticated ?? false)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Accounts" asp-action="Logout">Logout</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Accounts" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Accounts" asp-action="Register">Register</a>
                        </li>
                    }
                </ul>
                @if (User.Identity?.Name is not null)
                {
                    <p class="nav navbar-text">Hello, @User.Identity?.Name!</p>
                }
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - SlackOnMinimals - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>